server:
    port: 8080
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            enabled: true
            routes:
                -   id: catalog-service
                    uri: lb://CATALOG-SERVICE
                    predicates:
                        - Path=/api/catalogs/**
                    filters:
                        - StripPrefix=1 # Removes the /api prefix before forwarding to the backend
management:
    endpoints:
        web:
            exposure:
                include=*:
eureka:
    instance:
        client:
            serviceUrl:
                defaultZone: http://localhost:8761/eureka
debug: true
logging:
    level:
        org.springframework.cloud.gateway: DEBUG